/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author fjz
 */
public class ReportWindowManager extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    Manager manager;
    PreparedStatement pst;
    private String[] columnNames;
    private int column = 0;
    private int row = 0;
    Object[][] cellData;
    
    /**
     * Creates new form ReportWindow
     */
    public ReportWindowManager(Manager manager) {
        this.manager = manager;
        initComponents();
        this.setLocationRelativeTo(null);
        conn = JavaConnect.ConnecrDb();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Username");

        jLabel2.setText(manager.username);

        Report re = new Report();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            re.cellData,
            new String [] {
                "TranscationID", "Creator", "Type", "CargoName", "CargoType", "Amount",
                "Confirmed", "Srcwarehouse", "Dstwarehouse", "Damage", "Unitprice"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("TrasactionID");

        jLabel4.setText("Damage");

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jButton1)
                        .addGap(210, 210, 210)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(37, 37, 37)
                            .addComponent(jLabel2))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Integer transactionid = Integer.parseInt(jTextField1.getText());
            String sql1 = "select * from report where transactionid=" +transactionid;
            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            int operationType = rs.getInt(3);
            String name = rs.getString(4);
            String cargoType = rs.getString(5);
            int amount = rs.getInt(6);
            int src = rs.getInt(8);
            int dst = rs.getInt(9);
            float price = rs.getFloat(11);
            pst.close();
            rs.close();
            
            String sql = "update report set confirmed = 1, damage = ? where transactionid =" +transactionid;
            pst = conn.prepareStatement(sql);
            int damage = Integer.parseInt(jTextField2.getText());
            if(damage > amount){
                JOptionPane.showMessageDialog(null, "The Damage Amount Error!");
                return;
            }
            pst.setInt(1, damage);
            pst.execute();
            pst.close();
            
            if(operationType==1){
                //Imoprt
                //warehouse
                String sql2 = "select "+cargoType+" from warehouse where warehouseid =" +dst;
                pst = conn.prepareStatement(sql2);
                rs = pst.executeQuery();
                int origin = rs.getInt(1);
                pst.close();
                rs.close();
                String sql3 = "update warehouse set '"+cargoType+"' =" +(origin+amount-damage)+ " where warehouseid =" +dst;
                pst = conn.prepareStatement(sql3);
                pst.execute();
                pst.close();
                //cargo
                String sql_1 = "select max(id) from cargo";
                pst = conn.prepareStatement(sql_1);
                rs = pst.executeQuery();
                int maxid = rs.getInt(1);
                pst.close();
                rs.close();
                for(int i=1; i<=(amount-damage);i++){
                    pst=conn.prepareStatement("insert into cargo (name, type, id, warehouse_id, price) values(?,?,?,?,?)");
                    pst.setString(1, name);
                    pst.setString(2, cargoType);
                    pst.setInt(3, (i+maxid));
                    pst.setInt(4, dst);
                    pst.setFloat(5, price);
                    pst.executeUpdate();
                    pst.close();
                } 
            }
            else if(operationType==2){
                //Export
                //warehouse
                String sql4 = "select "+cargoType+" from warehouse where warehouseid=" +src;
                pst = conn.prepareStatement(sql4);
                rs = pst.executeQuery();
                int origin = rs.getInt(1);
                rs.close();
                pst.close();
                String sql5 = "update warehouse set '"+cargoType+"' =" + (origin-amount)+ " where warehouseid =" +src;
                pst = conn.prepareStatement(sql5);
                pst.execute();
                pst.close();
                //cargo
                int[] row = new int[amount];
                int count = 0;
                String sql_2 = "select * from cargo where name = '"+name+"' limit " + amount;
                System.out.println(sql_2);
                pst = conn.prepareStatement(sql_2);
                rs = pst.executeQuery();
                while(rs.next()){
                    row[count] = rs.getInt(3);
                    count+=1;
                }
                for(int i=0;i<=amount-1; i++){
                    System.out.println(row[i]);
                }
                rs.close();
                pst.close();
                for(int i=0; i<= (row.length)-1; i++){
                    pst=conn.prepareStatement("delete from cargo where id ="+row[i]);
                    pst.execute();
                    pst.close();
                }
            }
            else{
                //Shift
                //warehouse
                String sql6 = "select "+cargoType+" from warehouse where warehouseid=" +src;
                pst = conn.prepareStatement(sql6);
                rs = pst.executeQuery();
                int origin_src = rs.getInt(1);
                pst.close();
                rs.close();
                String sql7 = "update warehouse set '"+cargoType+"' =" + (origin_src-amount)+ " where warehouseid =" +src;
                pst = conn.prepareStatement(sql7);
                pst.execute();
                pst.close();
                String sql8 = "select "+cargoType+" from warehouse where warehouseid =" +dst;
                pst = conn.prepareStatement(sql8);
                rs = pst.executeQuery();
                int origin_dst = rs.getInt(1);
                pst.close();
                rs.close();
                String sql9 = "update warehouse set '"+cargoType+"' =" +(origin_dst+amount-damage)+ " where warehouseid =" +dst;
                pst = conn.prepareStatement(sql9);
                pst.execute();
                pst.close();
                //cargo
                int[] row = new int[amount];
                int count = 0;
                String sql_2 = "select * from cargo where name = '"+name+"' limit " + amount;
                System.out.println(sql_2);
                pst = conn.prepareStatement(sql_2);
                rs = pst.executeQuery();
                while(rs.next()){
                    row[count] = rs.getInt(3);
                    count+=1;
                }
                for(int i=0;i<=amount-1; i++){
                    System.out.println(row[i]);
                }
                rs.close();
                pst.close();
                for(int i=0; i<=(row.length)-1;i++){
                    pst=conn.prepareStatement("update cargo set warehouse_id ="+dst+" where id ="+ row[i]);
                    pst.execute();
                    pst.close();
                }
            }
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
        try{
            this.setVisible(false);
            ReportWindowManager rw = new ReportWindowManager(manager);
            rw.setVisible(true);
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        WarehouseManagerPage ob = new WarehouseManagerPage(manager);
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
}



